move *_attk.ogg .\ie\tempa.ogg
move *_bat1.ogg .\ie\temp8.ogg
move *_bat2.ogg .\ie\temp9.ogg
move *_bat3.ogg .\ie\tempg_.ogg
move *_heal.ogg .\ie\tempe.ogg
move *_flee.ogg .\ie\tempu_.ogg
move *_tant.ogg .\ie\temph_.ogg
move *_gard.ogg .\ie\tempt_.ogg
move *_hit1.ogg .\ie\templ.ogg
move *_hit2.ogg .\ie\tempn_.ogg
move *_hit3.ogg .\ie\tempo_.ogg
move *_dyin.ogg .\ie\temps_.ogg
move *_dead.ogg .\ie\tempm.ogg
move *_spel.ogg .\ie\temp6.ogg
move *_inff.ogg .\ie\temp2.ogg
move *_foll.ogg .\ie\tempb.ogg
move *_hide.ogg .\ie\temp5.ogg
move *_can.ogg .\ie\tempi.ogg
move *_done.ogg .\ie\tempj.ogg
move *_encm.ogg .\ie\temp3.ogg
move *_slct.ogg .\ie\tempf.ogg
move *_hi.ogg .\ie\tempg.ogg
move *_yes.ogg .\ie\tempk.ogg
move *_rest.ogg .\ie\tempc.ogg
move *_bore.ogg .\ie\tempd.ogg
move *_haha.ogg .\ie\tempz.ogg
move *_cuss.ogg .\ie\temp1.ogg
move *_say.ogg .\ie\temph.ogg
move *_good.ogg .\ie\temps.ogg

